version: '3.4'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    image: kanselarij/frontend-persberichten:latest
    links:
      - identifier:backend
    environment:
      EMBER_OAUTH_API_KEY: "bd0483de-67e3-4ccf-8fcc-1aff6ff29675"
      EMBER_OAUTH_BASE_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/auth"
      EMBER_OAUTH_REDIRECT_URL: "https://VLIVIA-dev.vlaanderen.be/authorization/callback"
      EMBER_OAUTH_LOGOUT_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/logout"
      EMBER_OAUTH_RETURN_URL: "https://VLIVIA-dev.vlaanderen.be"
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"},{\"variables\":[\"published\"],\"name\":\"unauthenticated-published\"},{\"variables\":[],\"name\":\"clean\"}]"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.7
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      DATABASE_COMPATIBILITY: "Virtuoso"
      DATABASE_OVERLOAD_RECOVERY: "on"
      LOG_OUTGOING_SPARQL_QUERIES: "on"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./data/db:/data
    restart: always
    logging: *default-logging
  delta-notifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    logging: *default-logging
  mock-login:
    image: kanselarij/mock-login-service:1.0.0
    restart: always
    logging: *default-logging
  login:
    image: kanselarij/press-releases-acmidm-login-service:0.1.0
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "bd0483de-67e3-4ccf-8fcc-1aff6ff29675"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://VLIVIA-dev.vlaanderen.be/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "THIS IS OUR SECRET"
    logging: *default-logging
    restart: always
    labels:
      - "logging=true"
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.20.0
    volumes:
      - ./config/resources:/config
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.1.2
    volumes:
      - ./data/files:/share
    restart: always
    logging: *default-logging
  csv-file-parser:
    image: kanselarij/csv-parser-service:0.1.0
    volumes:
      - ./data/files:/share
    restart: always
    logging: *default-logging
  collaboration:
    image: kanselarij/press-releases-collaboration-service:0.6.0
    restart: always
    logging: *default-logging
  publication-tasks-generator:
    image: kanselarij/press-releases-publication-tasks-generator-service:0.1.0
    restart: always
    logging: *default-logging
  email-publication:
    image: kanselarij/press-releases-email-generator-service:0.1.1
    restart: always
    logging: *default-logging
  belga-publication:
    image: kanselarij/press-releases-belga-publication-service:0.1.1
    volumes:
      - ./data/belga:/share
    environment:
      BELGA_FTP_USERNAME: 'username'
      BELGA_FTP_PASSWORD: 'password'
      BELGA_FTP_HOST: 'host'
    restart: always
    logging: *default-logging
  mail-delivery:
    image: redpencil/deliver-email-service:0.1.3
    environment:
      MAILBOX_URI: "http://themis.vlaanderen.be/id/mailboxes/8240e358-b914-47d7-9c9d-c873bcbb76d5"
      WELL_KNOWN_SERVICE: "test"
      EMAIL_ADDRESS: "noreply@vlivia.vlaanderen.be"
      EMAIL_CRON_PATTERN: "*/5 * * * *"
    volumes:
      - ./data/files:/share
    restart: always
    logging: *default-logging
  mailchimp-publication:
    image: kanselarij/press-releases-mailchimp-publication-service:0.1.0
    restart: always
    logging: *default-logging
    environment:
      MAILCHIMP_API: 'api key'
      MAILCHIMP_REPLY_TO: 'reply-to address'
      MAILCHIMP_FROM_NAME: Kaleidos-test
      MAILCHIMP_LIST_ID: 5480352579
      MAILCHIMP_INTEREST_CATEGORY_ID: fe04dcefd7
      MAILCHIMP_KIND_CATEGORY_ID: 4757bb85ec
  api-publication:
    image: kanselarij/press-releases-api-publication-service:0.1.0
    restart: always
    logging: *default-logging

