version: '3.4'

services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  triplestore:
    ports:
      - "8890:8890"
    restart: "no"
  delta-notifier:
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  file:
    restart: "no"
  mail-delivery:
    restart: "no"
